sudo: required

language: generic

services:
  - docker

#before_install:
#  - docker build . -t mosh2018/react-test -f ./fe_app/Dockerfile.dev .
#
#script:
#  - docker run -e CI=true mosh2018/react-test npm run test -- --coverage
before_install:
  - docker build . -t mosh2020/ui -f fe_app/Dockerfile
  - docker build . -t mosh2020/web -f be_app/Dockerfile
  - docker build . -t mosh2020/nginx -f nginx/Dockerfile

script:
#log to docker cli
  - echo "$DOCKER_PSSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push mosh2020/ui
  - docker push mosh2020/web
  - docker push mosh2020/nginx


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-149501274876
  bucket_path:  docker-multi
  on:
    branch: multi-docker
