version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'

  web:
    build:
      context: ./be_app/

    command: >
      sh -c "python ./be_app/manage.py migrate &&
             python ./be_app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "5005:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  ui:
    build:
      context: ./fe_app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./fe_app:/app
    ports:
      - "3005:3000"
